name: Sub Issue
description: Crear una tarea relacionada con una Historia de Usuario
title: "[Task] "
labels:
  - Task

body:

  - type: textarea
    id: description
    attributes:
      label: Descripción
      description: Describe el objetivo de la tarea.
      placeholder: |
        Implementar la funcionalidad necesaria para...

        La tarea deberá cumplir con los requerimientos definidos y mantener la línea visual o técnica establecida para el proyecto.
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: Tareas
      description: Lista de actividades necesarias para completar la tarea.
      placeholder: |
        - Crear la estructura necesaria.
        - Implementar la funcionalidad.
        - Realizar pruebas correspondientes.
        - Verificar integración con el sistema.
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Criterios de Aceptación
      description: Condiciones que deben cumplirse para considerar terminada la tarea.
      placeholder: |
        - La funcionalidad cumple con el objetivo definido.
        - La implementación funciona correctamente.
        - No existen errores críticos.
        - Se mantiene la calidad visual y técnica del proyecto.
    validations:
      required: true
