name: Backend CI

on: 
    push:
    pull_request:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Descargar el código del repo
              uses: actions/checkout@v4

            - name: Instalar Python
              uses: actions/setup-python@v5
              with:
                python-version: "3.12"

            - name: Instalar dependencias
              run: pip install -r requirements.txt

            - name: Revisar estilo del codigo con ruff
              run: ruff check